const data = {
  products: [
    {
      // _id: '1',
      name: 'Nike slim shirt',
      slug: 'nike-slim-shirts',
      catagory: 'shirts',
      image: '/images/p1.jpg',
      countInStock: 50,
      price: 120,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 4.5,
      description: 'high quality shirt',
    },

    {
      // _id: '2',
      name: 'Adidas slim shirt',
      slug: 'Adidas-slim-shirts',
      catagory: 'shirts',
      image: '/images/p2.jpg',
      countInStock: 0,
      price: 120,
      brand: 'Adidas',
      rating: 4.5,
      numReviews: 4.5,
      description: 'high quality shirt',
    },
    {
      // _id: '3',
      name: 'Nike slim shirt',
      slug: 'Nike-slim-shirts',
      catagory: 'shirts',
      image: '/images/p3.jpg',
      countInStock: 25,
      price: 120,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 4.5,
      description: 'high quality shirt',
    },
    {
      // _id: '4',
      name: 'adidas slim shirt',
      slug: 'adidas-slim-shirts',
      catagory: 'shirts',
      image: '/images/p4.jpg',
      countInStock: 20,
      price: 120,
      brand: 'adAdidas',
      rating: 4.5,
      numReviews: 4.5,
      description: 'high quality shirt',
    },
  ],
};

export default data;
